name: using a cdocker container action
on:
  push:
    branches: [dev,main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v4
      - name: using docker container action
        id: dockeraction
        uses: ./.github/actions/docker/
      - name: output of docker container
        run: |
          echo "the ouput from the container is ${{steps.dockeraction.outputs.message}}"

